services:

  postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=zs1
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timetabler
    volumes:
      - ./db-data:/var/lib/postgresql/data